create table category_tb
(
    id            bigint generated by default as identity
        primary key,
    category_name varchar(255) not null
);

alter table category_tb
    owner to postgres;

create table cusine_tb
(
    id           bigint generated by default as identity
        primary key,
    cuisine_name varchar(255) not null
);

alter table cusine_tb
    owner to postgres;

create table file_tb
(
    id       bigint generated by default as identity
        primary key,
    filename varchar(255),
    url      varchar(255)
);

alter table file_tb
    owner to postgres;

create table user_tb
(
    id                integer generated by default as identity
        primary key,
    created_at        timestamp default now(),
    email             varchar(100)
        constraint uk2dlfg6wvnxboknkp9d1h75icb
            unique,
    email_verified_at timestamp(6),
    user_name         varchar(250),
    is_email_verified boolean,
    password          varchar(80) not null,
    phone_number      varchar(20),
    profile_image     text,
    role              varchar(20)
);

alter table user_tb
    owner to postgres;

create table address_tb
(
    id                bigint generated by default as identity
        primary key,
    address_detail    varchar(255),
    latitude          double precision,
    longitude         double precision,
    tag               varchar(255),
    user_id           integer
        constraint fk79r2osjq808rvy407533do5i9
            references user_tb
            on delete cascade
);

alter table address_tb
    owner to postgres;

create table bank_tb
(
    id             bigint generated by default as identity
        primary key,
    account_name   varchar(255),
    account_number varchar(255),
    bank_logo      varchar(255),
    bank_name      varchar(255),
    currency       varchar(255)
        constraint bank_tb_currency_check
            check ((currency)::text = ANY ((ARRAY ['DOLLAR'::character varying, 'RIEL'::character varying])::text[])),
    user_id        integer
        constraint uksh3i2i5jrkow5bg8hgneubxlo
            unique
        constraint fk7s8jfg6babg59aytcupjwjjyb
            references user_tb
            on delete cascade
);

alter table bank_tb
    owner to postgres;

create table code_tb
(
    id           bigint generated by default as identity
        primary key,
    created_date timestamp default now(),
    email        varchar(255),
    expire_date  timestamp(6) not null,
    pin_code     varchar(255),
    user_id      integer
        constraint ukccfs9d37gn8cmmikhmitsyolh
            unique
        constraint fk3l5omi2n2hdbrvx0xtst5ryph
            references user_tb
            on delete cascade
);

alter table code_tb
    owner to postgres;

create table credential_tb
(
    id            bigint generated by default as identity
        primary key,
    account_no    varchar(255),
    client_id     varchar(255),
    client_secret varchar(255),
    user_id       integer
        constraint ukgn3eemy0r6fj7m6tcot7h3mtp
            unique
        constraint fkfmpjo1smq9jpbj7qh1ckp5ih4
            references user_tb
            on delete cascade
);

alter table credential_tb
    owner to postgres;

create table food_recipe_tb
(
    id                  bigint generated by default as identity
        primary key,
    average_rating      double precision,
    cooking_steps       jsonb,
    created_at          timestamp default now() not null,
    description         text,
    duration_in_minutes integer,
    ingredients         jsonb,
    level               varchar(50),
    name                varchar(255),
    total_raters        integer,
    updated_at          timestamp(6),
    category_id         bigint
        constraint fkgqyc0jtw8mldg3mn27oa2jogy
            references category_tb,
    cuisine_id          bigint
        constraint fkiko87h1p81ko69hvnnp1tms4p
            references cusine_tb,
    user_id             integer                 not null
        constraint fkch8f6uwhy7atp6jv5dvgfruf5
            references user_tb
            on delete cascade
);

alter table food_recipe_tb
    owner to postgres;

create table food_sell_tb
(
    id             bigint generated by default as identity
        primary key,
    amount         integer,
    currency_type  varchar(255),
    date_cooking   timestamp(6),
    is_orderable   boolean,
    price          double precision,
    food_recipe_id bigint
        constraint uk9n3q45gxchfjlcyvt0jr7qt33
            unique
        constraint fkjnh07eurlqfsgfrukru7l94h
            references food_recipe_tb
            on delete cascade
);

alter table food_sell_tb
    owner to postgres;

create table favorite_tb
(
    id             bigint generated by default as identity
        primary key,
    favorite_date  timestamp(6) not null,
    food_recipe_id bigint
        constraint fkomhtq2agok4elcodsj19rtud0
            references food_recipe_tb
            on delete cascade,
    food_sell_id   bigint
        constraint fkgffs66bsr5oxtdtvhau5pijic
            references food_sell_tb
            on delete cascade,
    user_id        integer      not null
        constraint fkf8yje2vlq4aswj92vxu1jsf42
            references user_tb
            on delete cascade
);

alter table favorite_tb
    owner to postgres;

create table feedback_tb
(
    id             bigint generated by default as identity
        primary key,
    comment_text   text,
    created_at     timestamp(6) not null,
    rating_value   integer,
    food_recipe_id bigint
        constraint fk3og1myjvr5pcg315l0uqfalw9
            references food_recipe_tb
            on delete cascade,
    food_sell_id   bigint
        constraint fkqxgiy5exninf3usqv8x5avwet
            references food_sell_tb
            on delete cascade,
    user_id        integer      not null
        constraint fk3exy75beew66jgdj9xiappwfq
            references user_tb
            on delete cascade
);

alter table feedback_tb
    owner to postgres;

create table photo_tb
(
    id             bigint generated by default as identity
        primary key,
    photo          varchar(255) not null,
    food_recipe_id bigint
        constraint fkqfns2xv28h7si4tlxt4gljey7
            references food_recipe_tb
            on delete cascade
);

alter table photo_tb
    owner to postgres;

create table purchase_tb
(
    id                   bigint generated by default as identity
        primary key,
    created_date         timestamp default now(),
    payment_type         varchar(255)
        constraint purchase_tb_payment_type_check
            check ((payment_type)::text = ANY ((ARRAY ['CASH'::character varying, 'KHQR'::character varying])::text[])),
    purchase_status_type varchar(255)
        constraint purchase_tb_purchase_status_type_check
            check ((purchase_status_type)::text = ANY
                   ((ARRAY ['ACCEPTED'::character varying, 'REJECTED'::character varying, 'PENDING'::character varying])::text[])),
    quantity             integer,
    remark               varchar(255),
    total_price          double precision,
    buyer_id             integer not null
        constraint fkqo8kfayecux21c1troa12pgu2
            references user_tb
            on delete cascade,
    food_sell_id         bigint
        constraint fk8j0pxybywfdorrf2l0nxphkvg
            references food_sell_tb
            on delete cascade
);

alter table purchase_tb
    owner to postgres;

create table reciept_tb
(
    id          bigint generated by default as identity
        primary key,
    paid_by     smallint
        constraint reciept_tb_paid_by_check
            check ((paid_by >= 0) AND (paid_by <= 1)),
    paid_date   timestamp(6),
    reference   varchar(255),
    status      varchar(255),
    purchase_id bigint
        constraint uko2j2g7phjtmyi2e7nj57p6ou
            unique
        constraint fksffxewqqbpftkxxbtgmqqhrck
            references purchase_tb
            on delete cascade
);

alter table reciept_tb
    owner to postgres;

create table notification_tb
(
    id           integer generated by default as identity
        primary key,
    created_date timestamp default now(),
    description  varchar(255),
    is_read      boolean   default false,
    receiver_id  integer
        constraint fkaplx7mt7tbbayd9fgx8t44q8k
            references user_tb
            on delete cascade,
    recipe_id    bigint
        constraint fkjfbibej4isktrijv7tbbsle65
            references reciept_tb
            on delete cascade,
    sender_id    integer
        constraint fkidsrwj1p4daglfbb2birwya5f
            references user_tb
            on delete cascade
);

alter table notification_tb
    owner to postgres;

create table token_tb
(
    token_id      integer generated by default as identity
        primary key,
    token         varchar(255)
        constraint uk93hdg770tkn0iueavyxgu4fgb
            unique,
    token_expired boolean,
    token_revoked boolean,
    token_type    varchar(255)
        constraint token_tb_token_type_check
            check ((token_type)::text = 'BEARER'::text),
    user_id       integer
        constraint fkb4kmvil2dffrtryldinm1f9vk
            references user_tb
            on delete cascade
);

alter table token_tb
    owner to postgres;

create table device_token_tb
(
    id           bigint generated by default as identity
        primary key,
    device_token varchar(255),
    user_id      integer
        constraint uk5ld01k2e03njfiu7ei9wx00qh
            unique
        constraint fke2w9but28wx494h0q6373sc6b
            references user_tb
);

alter table device_token_tb
    owner to postgres;

